

service: guestbook-serverless-demo-adam

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
  store-message:
    handler: store-message.storeMessage
    events:
      - http:
          path: storeMessage
          method: post
          integration: lambda
          cors: true
  get-messages:
    handler: get-messages.getMessages
    events:
      - http:
          path: getMessages
          method: get
          integration: lambda
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages
        AttributeDefinitions:
          - AttributeName: msg_id
            AttributeType: S
        KeySchema:
          - AttributeName: msg_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:*:*:table/messages
        Roles:
          - Ref: IamRoleLambdaExecution
